FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm
COPY ./packages ./packages



COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./turbo.json ./turbo.json

COPY ./apps/excalidraw-frontend ./apps/excalidraw-frontend
RUN pnpm install 

WORKDIR /usr/src/app/packages/db

RUN npx prisma generate 

WORKDIR /usr/src/app/apps/excalidraw-frontend



CMD ["pnpm","run","dev"]








