import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-satoshi bg-black `}
      >
          <Toaster theme="dark" richColors />

        <Providers>
        
        {children}
        </Providers>

      </body>
    </html>
  );
}
